### ISSUE TITLE
Command Handlers

### ISSUE THREAD

**Issue by SkyHawkB** [KyronBot/kyron#1]
This is about command handling.
For this we can use `fs` or `switch`.
Both have issues and advantages.

- `fs`
    - **Pros:**
    - cleaner/neater
    - more powerful
    - **Cons:**
    - harder to access files
    - limited globals
- `switch`
    - **Pros:**
    - all files and globals can be accessed
    - all in one file
    - **Cons:**
    - messy style-wise
    - conflicting variables can occur

So now we can see which one's better.
- [ ] `fs` (recommended)
- [ ] `switch` (easier & worse)

**Comment by ethamitc** [comment]
We will be running mainly FileSystem, but Switch for commands that dont work with FileSystem (eg. Check if Dev Commands).
